<?php

namespace App\Http\Controllers\Mahasiswa;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\View\View;

class RiwayatBimbinganController extends Controller
{
    public function index(): View
    {
        return view('mahasiswa.riwayat_bimbingan', [
            'mahasiswa' => [
                'nama' => 'Andi Pratama',
                'nim' => '2108107010001',
                'status' => 'Mahasiswa Aktif',
                'program_studi' => 'Informatika',
                'semester' => 'Semester 7',
                'angkatan' => '2021',
            ],
            'ringkasan' => [
                'total_sesi' => 16,
                'bimbingan_skripsi' => 10,
                'bimbingan_akademik' => 6,
                'total_acc' => 12,
                'total_revisi' => 4,
            ],
            'riwayat' => [
                [
                    'id' => 1,
                    'tanggal' => '11 Okt 2026',
                    'waktu' => '09.30 - 11.00 WIB',
                    'kategori' => 'Skripsi',
                    'badge_kategori' => 'primary',
                    'dosen' => 'Dr. Ir. Teuku Muhammad, M.T.',
                    'role_dosen' => 'Dosen Pembimbing Utama',
                    'topik' => 'BAB III: Review Flowchart & Class Diagram Sistem Bimbingan',
                    'dokumen' => 'Draft_BAB3_Diagram_v1.2.pdf',
                    'status' => 'ACC',
                    'badge_status' => 'primary',
                    'catatan' => 'Jadwal dan perancangan diagram telah disetujui. Dokumentasi foto sesi bimbingan terverifikasi.',
                    'foto' => 'assets/media/svg/avatars/001-boy.svg',
                    'ruangan' => 'Ruang Dosen 2.04 Fasilkom',
                ],
                [
                    'id' => 2,
                    'tanggal' => '04 Okt 2026',
                    'waktu' => '14.00 - 15.15 WIB',
                    'kategori' => 'Akademik',
                    'badge_kategori' => 'info',
                    'dosen' => 'Prof. Dr. Eng. Ir. Herman, M.T.',
                    'role_dosen' => 'Dosen Wali / DPA',
                    'topik' => 'Evaluasi Pengisian KRS Semester 7 & Persiapan Sidang Komprehensif',
                    'dokumen' => 'Form_KRS_Semester_7_Approved.pdf',
                    'status' => 'Selesai',
                    'badge_status' => 'success',
                    'catatan' => 'KRS Semester 7 sebanyak 24 SKS telah disetujui & ditandatangani secara digital.',
                    'foto' => 'assets/media/svg/avatars/002-boy-2.svg',
                    'ruangan' => 'Ruang Wali Lt. 1 R.108',
                ],
                [
                    'id' => 3,
                    'tanggal' => '28 Sep 2026',
                    'waktu' => '13.30 - 15.00 WIB',
                    'kategori' => 'Skripsi',
                    'badge_kategori' => 'primary',
                    'dosen' => 'Dr. Ir. Teuku Muhammad, M.T.',
                    'role_dosen' => 'Dosen Pembimbing Utama',
                    'topik' => 'BAB II: Tinjauan Pustaka & Matriks Comparative Literature',
                    'dokumen' => 'Draft_BAB2_ACC.pdf',
                    'status' => 'Selesai',
                    'badge_status' => 'success',
                    'catatan' => 'BAB II dinyatakan ACC dengan catatan kecil pada penulisan sitasi standar IEEE.',
                    'foto' => null,
                    'ruangan' => 'Zoom Online Meeting',
                ],
                [
                    'id' => 4,
                    'tanggal' => '20 Sep 2026',
                    'waktu' => '10.30 - 11.30 WIB',
                    'kategori' => 'Akademik',
                    'badge_kategori' => 'info',
                    'dosen' => 'Prof. Dr. Eng. Ir. Herman, M.T.',
                    'role_dosen' => 'Dosen Wali / DPA',
                    'topik' => 'Konsultasi Permohonan Surat Rekomendasi Beasiswa Djarum Plus',
                    'dokumen' => 'Surat_Rekomendasi_Beasiswa.pdf',
                    'status' => 'Selesai',
                    'badge_status' => 'success',
                    'catatan' => 'Surat Rekomendasi Beasiswa disetujui dan ditandatangani Dosen Wali.',
                    'foto' => 'assets/media/svg/avatars/004-boy-3.svg',
                    'ruangan' => 'Ruang DPA R.108',
                ],
                [
                    'id' => 5,
                    'tanggal' => '10 Sep 2026',
                    'waktu' => '10.00 - 11.30 WIB',
                    'kategori' => 'Skripsi',
                    'badge_kategori' => 'primary',
                    'dosen' => 'Dr. Ir. Teuku Muhammad, M.T.',
                    'role_dosen' => 'Dosen Pembimbing Utama',
                    'topik' => 'BAB I: Pendahuluan, Latar Belakang & Rumusan Masalah',
                    'dokumen' => 'Draft_BAB1_Final.pdf',
                    'status' => 'Selesai',
                    'badge_status' => 'success',
                    'catatan' => 'BAB I disetujui penuh. Mahasiswa diizinkan melanjutkan penyusunan BAB II.',
                    'foto' => 'assets/media/svg/avatars/002-boy-2.svg',
                    'ruangan' => 'Gedung Fasilkom R.204',
                ],
                [
                    'id' => 6,
                    'tanggal' => '25 Agu 2026',
                    'waktu' => '13.00 - 14.30 WIB',
                    'kategori' => 'Skripsi',
                    'badge_kategori' => 'primary',
                    'dosen' => 'Dr. Ir. Teuku Muhammad, M.T.',
                    'role_dosen' => 'Dosen Pembimbing Utama',
                    'topik' => 'Pengajuan Judul & Proposal Tugas Akhir',
                    'dokumen' => 'Proposal_Skripsi_Final.pdf',
                    'status' => 'Selesai',
                    'badge_status' => 'success',
                    'catatan' => 'Judul skripsi disetujui tim DPA dan Pembimbing Utama.',
                    'foto' => null,
                    'ruangan' => 'Ruang Dosen 2.04',
                ],
                [
                    'id' => 7,
                    'tanggal' => '15 Agu 2026',
                    'waktu' => '09.00 - 10.00 WIB',
                    'kategori' => 'Akademik',
                    'badge_kategori' => 'info',
                    'dosen' => 'Prof. Dr. Eng. Ir. Herman, M.T.',
                    'role_dosen' => 'Dosen Wali / DPA',
                    'topik' => 'Evaluasi KHS Semester 6 & Perencanaan SKS Semester 7',
                    'dokumen' => 'KHS_Semester_6_Verified.pdf',
                    'status' => 'Selesai',
                    'badge_status' => 'success',
                    'catatan' => 'IPK Semester 6 dicapai 3.82. Mempertahankan predikat Cumlaude.',
                    'foto' => null,
                    'ruangan' => 'Ruang Wali R.108',
                ],
                [
                    'id' => 8,
                    'tanggal' => '02 Agu 2026',
                    'waktu' => '11.00 - 12.00 WIB',
                    'kategori' => 'Skripsi',
                    'badge_kategori' => 'primary',
                    'dosen' => 'Dr. Ir. Teuku Muhammad, M.T.',
                    'role_dosen' => 'Dosen Pembimbing Utama',
                    'topik' => 'BAB I: Review Batasan Masalah & Lingkup Penelitian',
                    'dokumen' => 'Draft_BAB1_Rev1.pdf',
                    'status' => 'Revisi',
                    'badge_status' => 'danger',
                    'catatan' => 'Perbaiki batasan masalah pada bagian scope latency microservices.',
                    'foto' => null,
                    'ruangan' => 'Gedung Fasilkom R.204',
                ],
            ],
            'dosen_list' => [
                'Dr. Ir. Teuku Muhammad, M.T.' => 'Dosen Pembimbing Skripsi',
                'Prof. Dr. Eng. Ir. Herman, M.T.' => 'Dosen Wali (DPA)',
            ],
            'notifikasi' => [
                [
                    'judul' => 'Dokumentasi Bimbingan BAB III disetujui Dosen Pembimbing',
                    'waktu' => '2 jam yang lalu',
                ],
                [
                    'judul' => 'KRS Semester 7 disetujui Dosen Wali',
                    'waktu' => '5 hari yang lalu',
                ],
            ],
        ]);
    }
}
